### ISSUE TITLE
requirements.txt中36行符号错了

### ISSUE THREAD

**Issue by Big-yellowa** [GPTScan/GPTScan#5]
pygments==2.18.0

**Comment by Big-yellowa** [comment]
Traceback (most recent call last):
  File "/root/autodl-tmp/GPTScan/src/main.py", line 13, in <module>
    import tasks
  File "/root/autodl-tmp/GPTScan/src/tasks.py", line 8, in <module>
    import falcon_adapter
  File "/root/autodl-tmp/GPTScan/src/falcon_adapter.py", line 4, in <module>
    from falcon.__main__ import process_single, get_detectors_and_printers, parse_args
ModuleNotFoundError: No module named 'falcon.__main__'为什么会出现这个错误

**Comment by melody27** [comment]
whether solve the promble

> Traceback (most recent call last): File "/root/autodl-tmp/GPTScan/src/main.py", line 13, in import tasks File "/root/autodl-tmp/GPTScan/src/tasks.py", line 8, in import falcon_adapter File "/root/autodl-tmp/GPTScan/src/falcon_adapter.py", line 4, in from falcon.**main** import process_single, get_detectors_and_printers, parse_args ModuleNotFoundError: No module named 'falcon.**main**'为什么会出现这个错误


Have you solved this problem yet? I’m encountering the same issue.

**Comment by melody27** [comment]
解决了， 卸载了falcon。然后重新在其他目录安装了falcon，然后打了个软链接从pip的第三方库列表，链接到falcon下面同名子目录falcon。 
另外还比如from falcon import Falcon报错。修改成from falcon.falcon import Falcon就好了

**Comment by e-Ricardo** [comment]
> Traceback (most recent call last): File "/root/autodl-tmp/GPTScan/src/main.py", line 13, in import tasks File "/root/autodl-tmp/GPTScan/src/tasks.py", line 8, in import falcon_adapter File "/root/autodl-tmp/GPTScan/src/falcon_adapter.py", line 4, in from falcon.**main** import process_single, get_detectors_and_printers, parse_args ModuleNotFoundError: No module named 'falcon.**main**'为什么会出现这个错误

请问解决了吗

**Comment by e-Ricardo** [comment]
> 解决了， 卸载了falcon。然后重新在其他目录安装了falcon，然后打了个软链接从pip的第三方库列表，链接到falcon下面同名子目录falcon。 另外还比如from falcon import Falcon报错。修改成from falcon.falcon import Falcon就好了

求解什么意思，在哪个其他目录安装falcon，再做软连接。我在anaconda开的单独虚拟环境，pycharm，mac，感谢🙏，也被这个问题困扰

**Comment by Billy1900** [comment]
> > 解决了， 卸载了falcon。然后重新在其他目录安装了falcon，然后打了个软链接从pip的第三方库列表，链接到falcon下面同名子目录falcon。 另外还比如from falcon import Falcon报错。修改成from falcon.falcon import Falcon就好了
> 
> 求解什么意思，在哪个其他目录安装falcon，再做软连接。我在anaconda开的单独虚拟环境，pycharm，mac，感谢🙏，也被这个问题困扰

Please install this package via this link: https://github.com/MetaTrustLabs/falcon-metatrust

**Comment by Elkdx** [comment]
> 解决了， 卸载了falcon。然后重新在其他目录安装了falcon，然后打了个软链接从pip的第三方库列表，链接到falcon下面同名子目录falcon。 另外还比如from falcon import Falcon报错。修改成from falcon.falcon import Falcon就好了

请问你运行完了吗，可以给我看看你检测的solidity项目和对应的output.json吗，我想看看这个项目的结构，但是我运行不出来
